#!/usr/bin/python2
#coding=utf-8
# Le credit pour ce code va a Mr Hacker_K
# Si vous voulez prendre Le credit pour ce code Voyez Faster Axel.


import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
from getpass import getpass

def faxel():
    mr = [
     '*Faxel*', '      ', '*McTony*', '      ', '*Faxel*', '      ', '*McTony*', '      ', '*Faxel*', '      ', '*Faxel*', '      ', '*McTony*', '      ', '*Faxel*', '      ', '*Faxel*', '      ', '*McTony*', '      ', '*Faxel*', '      ', '*Faxel*', '      ', '*McTony*', '      ', '*Faxel*', '      ', '*Faxel*', '      ', '*Faxel*', '      ', '*McTony*', '      ', '*Faxel*', '      ', '*Faxel*', '      ', '*McTony*\n']
    for o in mr:
        print '\r\x1b[1;97m[\x1b[1;32m●●\x1b[1;97m]   [38;5;221m  ' + o,
        sys.stdout.flush()
        time.sleep(0.15)

	
	
os.system('clear')
####################################################################################################	
print"[38;5;214m<════════════════════\033[1;97mConnexion a[38;5;245m Mr \033[48;5;0;38;5;197mHacker_K[38;5;214m════════════════════>"
Nu = "Hacker_K"
print("")
mdp = "08127934"
loop = 'true'
while (loop == 'true'):
    Nomu = raw_input("\033[1;91m[\033[1;97m**\033[1;91m] \x1b[1;97mNom d'utilisateur de l'outil \x1b[1;91m»»»» [48;5;0;38;5;197m")
    if (Nomu == Nu):
    	md = raw_input("\033[1;91m[\033[1;97m++\033[1;91m] \x1b[1;97mMot de passe de l'outil      \x1b[1;91m»»»» [38;5;245m")
        if (md == mdp):	
	    print("")	       
	    print"[38;5;214m<════════════════════\033[1;97mConnexion a[38;5;245m Mr \033[48;5;0;38;5;197mHacker_K[38;5;214m════════════════════>"
	    McTony()
	    print("")
            print "\033[1;91m[\033[1;92m●●\033[1;91m] \033[1;97mConnecté en tant que \033[1;96m"  +  Nomu #Dev:Kouadio_Antoine
	    time.sleep(1)
            loop = 'false'
        else:
            print "\033[1;91m[\033[1;97mxx\033[1;91m] \033[1;93mMot de passe incorrect!!"
            os.system('xdg-open https://wa.me/22555709610')
    else:
         print "\033[1;91m[\033[1;97mxx\033[1;91m] \033[1;94mNom d'utilisateur incorrect!!"
         os.system('xdg-open https://t.me/Faxelh')	


def connexion():
	
      while True:
           os.system("clear")        
           try:
           
                os.system('date | lolcat')
                print("\033[1;97m╔"+44*"═"+1*"═╗")
	        print "\033[1;97m║[1;97m                                             ║"
	        print "\033[1;97m║[1;91m[[38;5;245mYoutube[48;5;0;38;5;194m FASTER AXEL[1;91m][1;97m                        ║"
	        print "\033[1;97m║[1;97m                                             ║"
	        print "\033[1;97m║[38;5;245mMr [38;5;221mHacker_K[1;97m vous salut dans la paix du [48;5;0;38;5;198mCHRIST[1;97m║"
	        print "\033[1;97m║[1;97m                                             ║"
	        print "\033[1;97m║[38;5;112mAuteur    [1;91m: [38;5;245m Mr [38;5;221mHacker_K[1;97m                     ║"
	        print "\033[1;97m║[38;5;115mCopyright [1;91m: [38;5;221m © 2020 [1;97m                         ║" 
	        print "\033[1;97m║[1;97m                                             ║"
	        print "\033[1;97m║[1;93m       ▶▶▶▶[1;91m  [[38;5;116m Bonjour a tous[1;91m][1;93m   ▶▶▶▶[1;97m        ║" 
	        print("\033[1;97m╚"+44*"═"+1*"═╝")   
	        print "\033[1;97m║"
	        nu=raw_input("\033[1;97m╚═\033[1;31m▶[38;5;221m  NOM UTILISATEUR \033[1;31m: [48;5;0;38;5;197m")
                print "\033[1;97m║"
                mp = getpass('\033[1;97m╚═\033[1;31m▶[38;5;221m MOT DE PASSE    \033[1;31m: [38;5;214m')
                print ("")
                if nu==usr and mp==pwd:
                   os.system("sleep 5;cd;clear")
                   faxel()
                   os.system('clear')
                   print('[38;5;214m<═══════════════════════════════════════> ')
                   os.system('figlet ' + nu + ' | lolcat')
                   print('[38;5;214m<═══════════════════════════════════════> ')
                   break
                else:
                      print("")
                      print("")
                      print("")
                      print("")
                      print("\x1b[91m			Accès refusé !")
                      time.sleep(2)
                      print("")
           except Exception:
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("[38;5;108m			Accès refusé !")
                      time.sleep(2)
           except KeyboardInterrupt:
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      os.system('killall -9 com.termux')
  
connexion()
