#!/usr/bin/python2
#coding=utf-8
# Le credit pour ce code va a :🄼🅁 🄵🄰🅇🄴🄻
# Si vous voulez prendre Le credit pour ce code Voyez 🄵🄰🅇🄴🄻.

import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
from getpass import getpass

def faxel():
    mr = [
     '*Faxel*', '      ', '*McTony*', '      ', '*Faxel*', '      ', '*McTony*', '      ', '*Faxel*', '      ', '*Faxel*', '      ', '*McTony*', '      ', '*Faxel*', '      ', '*Faxel*', '      ', '*McTony*', '      ', '*Faxel*', '      ', '*Faxel*', '      ', '*McTony*', '      ', '*Faxel*', '      ', '*Faxel*', '      ', '*Faxel*', '      ', '*McTony*', '      ', '*Faxel*', '      ', '*Faxel*', '      ', '*McTony*\n']
    for o in mr:
        print '\r\x1b[1;97m[\x1b[1;32m●●\x1b[1;97m]   [38;5;221m  ' + o,
        sys.stdout.flush()
        time.sleep(0.15)
		
os.system("clear")  
def connexion():
	
      while True:
           os.system("clear")        
           try:
                os.system('date | lolcat')
                print("\033[1;97m╔"+44*"═"+1*"═╗")
	        print "\033[1;97m║[1;97m                                             ║"
	        print "\033[1;97m║[1;91m[[38;5;245mYoutube[48;5;0;38;5;194m FASTER AXEL[1;91m][1;97m                        ║" 
	        print "\033[1;97m║[1;97m                                             ║"
	        print "\033[1;97m║[38;5;245mMr [38;5;221mFaxel[1;97m vous salut dans la paix du [48;5;0;38;5;198mCHRIST   [1;97m║"
	        print "\033[1;97m║[1;97m                                             ║"
	        print "\033[1;97m║[38;5;112mAuteur    [1;91m: [38;5;245m Mr [38;5;221mFaxel[1;97m                        ║"
	        print "\033[1;97m║[38;5;115mCopyright [1;91m: [38;5;221m © 2020 [1;97m                         ║" 
	        print "\033[1;97m║[1;97m                                             ║"
	        print "\033[1;97m║[1;93m       ▶▶▶▶[1;91m  [[38;5;116m Bonjour a tous[1;91m][1;93m   ▶▶▶▶[1;97m        ║" 
	        print("\033[1;97m╚"+44*"═"+1*"═╝")   
	        print "\033[1;97m║"
	        nu=raw_input("\033[1;97m╚═\033[1;31m▶[38;5;221m NOM UTILISATEUR \033[1;31m: [48;5;0;38;5;197m")
                print "\033[1;97m║"
                mp = getpass('\033[1;97m╚═\033[1;31m▶[38;5;221m MOT DE PASSE    \033[1;31m: [38;5;214m')
                print ("")
		faxel()
                if nu==usr and mp==pwd:
                   os.system("sleep 5;cd;clear")
                   os.system('clear')
                   print('[38;5;214m<═══════════════════════════════════════> ')
                   os.system('figlet ' + nu + ' | lolcat')
                   print('[38;5;214m<═══════════════════════════════════════> ')
                   break
                else:
                      print("")
                      print("")
                      print("")
                      print("")
                      print("\x1b[91m			Accès refusé !")
                      time.sleep(2)
                      print("")
           except Exception:
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("[38;5;108m			Accès refusé !")
                      time.sleep(2)
           except KeyboardInterrupt:
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      os.system('killall -9 com.termux')
  
connexion()
